### ISSUE TITLE
Rules are added multiple times

### ISSUE THREAD

**Issue by jobveldhuis** [jackmanapp/treeshake#12]
Say we take a html file:
```html
<h1>Test</h1>
<h1>Another test</h1>
<p>This is beautiful</p>
```

And a CSS file:
```css
h1 {
    color: red;
}

p {
    background-color: blue;
}

span {
    color: white;
}
```

After running Treeshake, we would expect the following output:
```css
h1 {
    color: red;
}

p {
    background-color: blue;
}
```

Running experiments with `v0.2.1` gives the following output:
```css
h1 {
    color: red;
}

p {
    background-color: blue;
}

h1 {
    color: red;
}
```
