### ISSUE TITLE
Element selectors like :hover do not work

### ISSUE THREAD

**Issue by jobveldhuis** [jackmanapp/treeshake#16]
Say we have a page that has some links:
```html
<a href="#">Test link</a>
```

And our css looks like this:
```css
a {
    color: red;
}

a:hover {
    color: blue;
}
```

We should expect that both the hover and the regular state are transformed into the css. Currently, the output will be as follows:

```css
a {
    color: red;
}
```
